bento_bros/bento_bros/urls.py
from django.contrib import admin
from django.urls import path
from menu.views import home_page, item, appetizer_item, seed, main_item, dessert_item

app_name = "menu"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_page),
    path('item/<int:index>', item),
    path('seed/', seed),
    path('appetizer_item/<int:appetizer_item_id>',
         appetizer_item, name="appetizer_item"),
    path('main_item/<int:main_item_id>',
         main_item, name="main_item"),
    path('dessert_item/<int:dessert_item_id>',
         dessert_item, name="dessert_item"),
]

bento_bros/menu/urls.py
from django.contrib import admin
from django.urls import path
from menu.views import appetizer_records, main_records, dessert_records, delete_app, delete_main, delete_dessert, update_app, update_main, update_dessert, create_dessert, create_main, create_app

app_name = "menu"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', appetizer_records, name="app_record"),
    path('main/', main_records, name="main_record"),
    path('dessert/', dessert_records, name="dessert_record"),
    path('delete_app/<int:appetizer_record_id>',
         delete_app, name="delete_app"),
    path('delete_main/<int:main_record_id>',
         delete_main, name="delete_main"),
    path('delete_dessert/<int:dessert_record_id>',
         delete_dessert, name="delete_dessert"),
    path('update_app/<int:appetizer_record_id>',
         update_app, name="update_app"),
    path('update_main/<int:main_record_id>',
         update_main, name="update_main"),
    path('update_dessert/<int:dessert_record_id>',
         update_dessert, name="update_dessert"),
    path('create_dessert/',
         create_dessert, name="create_dessert"),
    path('create_main/',
         create_main, name="create_main"),
    path('create_app/',
         create_app, name="create_app"),
]

bento_bros/menu/models.py
from django.db import models

# Create your models here.


class Appetizer(models.Model):
    name = models.CharField(max_length=50)
    japanese_name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    description = models.TextField(max_length=150)
    # id = models.IntegerField(primary_key=True, default=0)

    def __str__(self):
        return self.name


class MainCourse(models.Model):
    name = models.CharField(max_length=50)
    japanese_name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    description = models.TextField(max_length=150)
    # id = models.IntegerField(primary_key=True, default=0)

    def __str__(self):
        return self.name


class Dessert(models.Model):
    name = models.CharField(max_length=50)
    japanese_name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    description = models.TextField(max_length=150)
    # id = models.IntegerField(primary_key=True, default=0)

    def __str__(self):
        return self.name

bento_bros/menu/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from menu.models import Appetizer, MainCourse, Dessert
from menu.form import AppForm, MainForm, DessertForm

# Create your views here.
menu = [
    {
        "type": "appetizer",
        "price": 6.99,
        "name": "Gyoza",
        "japanese_name": "餃子",
        "description": "Delicious pan-fried dumplings filled with seasoned ground pork and vegetables. Served with a tangy soy dipping sauce."
    },
    {
        "type": "appetizer",
        "price": 5.99,
        "name": "Edamame",
        "japanese_name": "枝豆",
        "description": "Steamed young soybeans lightly seasoned with sea salt. A classic and healthy Japanese appetizer."
    },
    {
        "type": "appetizer",
        "price": 7.99,
        "name": "Agedashi Tofu",
        "japanese_name": "揚げ出し豆腐",
        "description": "Deep-fried tofu served in a flavorful dashi broth with grated daikon, green onions, and bonito flakes."
    },
    {
        "type": "appetizer",
        "price": 8.99,
        "name": "Takoyaki",
        "japanese_name": "たこ焼き",
        "description": "Savory octopus-filled batter balls cooked to perfection and topped with takoyaki sauce, mayonnaise, and bonito flakes."
    },
    {
        "type": "main course",
        "price": 12.99,
        "name": "Teriyaki Chicken",
        "japanese_name": "照り焼きチキン",
        "description": "Grilled chicken marinated in a sweet and savory teriyaki sauce. Served with steamed rice and a side of mixed vegetables."
    },
    {
        "type": "main course",
        "price": 14.99,
        "name": "Sushi Platter",
        "japanese_name": "寿司盛り合わせ",
        "description": "A delightful assortment of fresh nigiri and maki sushi. Chef's selection may include tuna, salmon, shrimp, and vegetable rolls."
    },
    {
        "type": "main course",
        "price": 15.99,
        "name": "Beef Yakiniku",
        "japanese_name": "焼肉",
        "description": "Thinly sliced beef marinated in a flavorful soy-based sauce and grilled to perfection. Served with a side of rice and kimchi."
    },
    {
        "type": "main course",
        "price": 13.99,
        "name": "Vegetable Tempura",
        "japanese_name": "野菜天ぷら",
        "description": "Assorted lightly battered and deep-fried seasonal vegetables. Served with a dipping sauce and steamed rice."
    },
    {
        "type": "main course",
        "price": 11.99,
        "name": "Tonkatsu",
        "japanese_name": "とんかつ",
        "description": "Crispy breaded and deep-fried pork cutlet served with shredded cabbage, tonkatsu sauce, and steamed rice."
    },
    {
        "type": "main course",
        "price": 16.99,
        "name": "Unagi Don",
        "japanese_name": "鰻丼",
        "description": "Grilled freshwater eel glazed with a sweet soy-based sauce. Served over a bed of steamed rice and garnished with pickles."
    },
    {
        "type": "main course",
        "price": 18.99,
        "name": "Ramen",
        "japanese_name": "ラーメン",
        "description": "A comforting bowl of flavorful broth, ramen noodles, and various toppings such as chashu pork, bamboo shoots, and a soft-boiled egg."
    },
    {
        "type": "main course",
        "price": 12.99,
        "name": "Chicken Katsu Curry",
        "japanese_name": "チキンカツカレー",
        "description": "Deep-fried breaded chicken cutlet served with Japanese curry sauce and steamed rice. A perfect combination of crispy and savory flavors."
    },
    {
        "type": "main course",
        "price": 17.99,
        "name": "Sashimi Deluxe",
        "japanese_name": "刺身デラックス",
        "description": "A premium selection of fresh sashimi, including tuna, salmon, yellowtail, and octopus. Served with wasabi, soy sauce, and pickled ginger."
    },
    {
        "type": "dessert",
        "price": 6.99,
        "name": "Matcha Green Tea Ice Cream",
        "japanese_name": "抹茶アイスクリーム",
        "description": "Creamy and refreshing matcha green tea-flavored ice cream. A perfect ending to your Japanese meal."
    },
    {
        "type": "dessert",
        "price": 7.99,
        "name": "Mochi Ice Cream",
        "japanese_name": "もちアイスクリーム",
        "description": "Chewy mochi rice cake filled with various flavors of ice cream, such as strawberry, mango, and green tea."
    },
    {
        "type": "dessert",
        "price": 5.99,
        "name": "Dorayaki",
        "japanese_name": "どら焼き",
        "description": "Sweet red bean paste sandwiched between two fluffy pancakes. A popular traditional Japanese dessert."
    }
]


def home_page(request):
    return render(request, "home_page.html", {'menu': menu})


def item(request, index):
    item = menu[index]
    return render(request, 'item_description.html', {'item': item})


def appetizer_item(request, appetizer_item_id):
    appetizer_item = get_object_or_404(Appetizer, id=appetizer_item_id)
    return render(request, "seed_item.html", {"item": appetizer_item})


def main_item(request, main_item_id):
    main_item = get_object_or_404(MainCourse, id=main_item_id)
    return render(request, "seed_item.html", {"item": main_item})


def dessert_item(request, dessert_item_id):
    dessert_item = get_object_or_404(Dessert, id=dessert_item_id)
    return render(request, "seed_item.html", {"item": dessert_item})


def appetizer_records(request):
    app_record = Appetizer.objects.all()
    return render(request, 'back_office.html', {"app_records": app_record})


def delete_app(request, appetizer_record_id):
    appetizer_record = get_object_or_404(Appetizer, id=appetizer_record_id)

    if request.method == 'POST':
        appetizer_record.delete()
        return render(request, 'back_office.html', {"deleted_item": appetizer_record})
    else:
        return HttpResponseNotAllowed(['POST'])


def update_app(request, appetizer_record_id):
    appetizer_record = get_object_or_404(Appetizer, id=appetizer_record_id)

    if request.method == 'POST':
        form = AppForm(request.POST, instance=appetizer_record)
        if form.is_valid():
            form.save()
    else:
        form = AppForm(instance=appetizer_record)
    context = {
        'form': form,
        'app_list': Appetizer.objects.all()
    }
    return render(request, 'edit.html', context)


def create_app(request):

    if request.method == 'POST':
        form = AppForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = AppForm()
    context = {
        'form': form,
    }
    return render(request, 'create.html', context)


def main_records(request):
    main_record = MainCourse.objects.all()
    return render(request, 'back_office.html', {"main_records": main_record})


def delete_main(request, main_record_id):
    main_record = get_object_or_404(MainCourse, id=main_record_id)

    if request.method == 'POST':
        main_record.delete()
        return render(request, 'back_office.html', {"deleted_item": main_record})
    else:
        return HttpResponseNotAllowed(['POST'])


def update_main(request, main_record_id):
    main_record = get_object_or_404(MainCourse, id=main_record_id)

    if request.method == 'POST':
        form = MainForm(request.POST, instance=main_record)
        if form.is_valid():
            form.save()
    else:
        form = MainForm(instance=main_record)
    context = {
        'form': form,
        'main_list': MainCourse.objects.all()
    }
    return render(request, 'edit.html', context)


def create_main(request):

    if request.method == 'POST':
        form = MainForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = MainForm()
    context = {
        'form': form,
    }
    return render(request, 'create.html', context)


def dessert_records(request):
    dessert_record = Dessert.objects.all()
    return render(request, 'back_office.html', {"dessert_records": dessert_record})


def delete_dessert(request, dessert_record_id):
    dessert_record = get_object_or_404(Dessert, id=dessert_record_id)

    if request.method == 'POST':
        dessert_record.delete()
        # return redirect('')
        return render(request, 'back_office.html', {"deleted_item": dessert_record})
    else:
        return HttpResponseNotAllowed(['POST'])


def update_dessert(request, dessert_record_id):
    dessert_record = get_object_or_404(Dessert, id=dessert_record_id)

    if request.method == 'POST':
        form = DessertForm(request.POST, instance=dessert_record)
        if form.is_valid():
            form.save()
    else:
        form = DessertForm(instance=dessert_record)
    context = {
        'form': form,
        'dessert_list': Dessert.objects.all()
    }
    return render(request, 'edit.html', context)


def create_dessert(request):

    if request.method == 'POST':
        form = DessertForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = DessertForm()
    context = {
        'form': form,
    }
    return render(request, 'create.html', context)


def seed(request):
    if not Appetizer.objects.exists():
        appetizers = [
            Appetizer(name="Gyoza", price=6.99,
                      description="Delicious pan-fried dumplings filled with seasoned ground pork and vegetables. Served with a tangy soy dipping sauce."),
            Appetizer(name="Edamame", price=5.99,
                      description="Steamed young soybeans lightly seasoned with sea salt. A classic and healthy Japanese appetizer."),
            Appetizer(name="Agedashi Tofu", price=7.99,
                      description="Deep-fried tofu served in a flavorful dashi broth with grated daikon, green onions, and bonito flakes."),
            Appetizer(name="Takoyaki", price=8.99,
                      description="Savory octopus-filled batter balls cooked to perfection and topped with takoyaki sauce, mayonnaise, and bonito flakes.")
        ]

bento_bros/menu/templates/back_office.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1><a href="../app">Appetizers</a></h1>
    {% for appetizer in app_records %}
    <h2>{{ appetizer.name }} ${{ appetizer.price }}</h2>
    <form action="{% url 'menu:update_app' appetizer.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="delete" value="PUT">Edit</button>
    </form>
    <form action="{% url 'menu:delete_app' appetizer.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="delete" value="DELETE">Delete</button>
    </form>
    {% endfor %}

    <h1><a href="../main">Main Course</a></h1>
    {% for main_course in main_records %}
    <h2>{{ main_course.name }} ${{ main_course.price }}</h2>
    <form action="{% url 'menu:update_main' main_course.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="delete" value="PUT">Edit</button>
    </form>
    <form action="{% url 'menu:delete_main' main_course.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="delete" value="DELETE">Delete</button>
    </form>
    {% endfor %}

    <h1><a href="../dessert">Desserts</a></h1>
    {% for dessert in dessert_records %}
    <h2>{{ dessert.name }} ${{ dessert.price }}</h2>
    <form action="{% url 'menu:update_dessert' dessert.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="delete" value="PUT">Edit</button>
    </form>
    <form action="{% url 'menu:delete_dessert' dessert.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="delete" value="DELETE">Delete</button>
    </form>
    {% endfor %}
    <form action="{% url 'menu:create_main' %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="delete" value="POST">Create +</button>
    </form>
  </body>
</html>

bento_bros/menu/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav>
      <ul>
        <li><a href="http://127.0.0.1:8000/home/">home</a></li>
        <li><a href="/">about</a></li>
        <li><a href="/">contact</a></li>
      </ul>
    </nav>
    <div>{% block content %}{% endblock %}</div>
  </body>
</html>

bento_bros/menu/templates/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create</title>
  </head>
  <body>
    <h1><a href="../app">BACK</a></h1>
    <h1>Create New Appetizer</h1>
    <form action="{% url 'menu:create_app' %}" method="POST">
      {% csrf_token %} {{ form }}
      <button type="submit">Create</button>
    </form>
    <h1>Create New Main Course</h1>
    <form action="{% url 'menu:create_main' %}" method="POST">
      {% csrf_token %} {{ form }}
      <button type="submit">Create</button>
    </form>

    <h1>Create New Dessert</h1>
    <form action="{% url 'menu:create_dessert' %}" method="POST">
      {% csrf_token %} {{ form }}
      <button type="submit">Create</button>
    </form>
  </body>
</html>

bento_bros/menu/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Edit</title>
  </head>
  <body>
    <h1><a href="../app">BACK</a></h1>
    {% for appetizer in app_list %}
    <form action="{% url 'menu:update_app' appetizer.id %}" method="POST">
      {% csrf_token %}
      <h2>{{ appetizer.name }}</h2>
      {{ form }}
      <button type="submit">Update</button>
    </form>
    {% endfor %} {% for main in main_list %}
    <form action="{% url 'menu:update_main' main.id %}" method="POST">
      {% csrf_token %}
      <h2>{{ main.name }}</h2>
      {{ form }}
      <button type="submit">Update</button>
    </form>
    {% endfor %} {% for dessert in dessert_list %}
    <form action="{% url 'menu:update_dessert' dessert.id %}" method="POST">
      {% csrf_token %}
      <h2>{{ dessert.name }}</h2>
      {{ form }}
      <button type="submit">Update</button>
    </form>
    {% endfor %}
  </body>
</html>

bento_bros/menu/templates/item_description.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% extends 'home_page.html' %}
    <title>{% block title %}Item Description{% endblock %}</title>
  </head>
  <body>
    <div>
      <ul>
        {% block content %}
        <li>
          <h3>{{ item.name }} {{ item.price }}</h3>
          <p>{{ item.description}}</p>
        </li>
        {% endblock %}
      </ul>
    </div>
  </body>
</html>

bento_bros/menu/templates/seed_item.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% extends 'home_page.html' %}
    <title>{% block title %}Item Description{% endblock %}</title>
  </head>
  <body>
    <div>
      <ul>
        {% block content %}
        <li>
          <h3>{{ item.name }} {{ item.price }}</h3>
          <p>{{ item.description }}</p>
        </li>
        {% endblock %}
      </ul>
    </div>
  </body>
</html>